changes

diff --git a/installation/Vault_Cluster/install_vault b/installation/Vault_Cluster/install_vault
--- a/installation/Vault_Cluster/install_vault
+++ b/installation/Vault_Cluster/install_vault
@@ -220,7 +220,6 @@ function install_binary {
 
   local -r bin_dir="$install_path/bin"
   local -r vault_dest_path="$bin_dir/vault"
-#   local -r run_vault_dest_path="$bin_dir/run-vault"
 
   unzip -d /tmp "$DOWNLOAD_PACKAGE_PATH"
   
@@ -229,14 +228,6 @@ function install_binary {
   sudo mv "/tmp/vault" "$SYSTEM_BIN_DIR/vault"
   sudo chown "$username:$username" "$SYSTEM_BIN_DIR/vault"
   sudo chmod a+x "$SYSTEM_BIN_DIR/vault"
-
-#   local -r symlink_path="$SYSTEM_BIN_DIR/vault"
-#   if [[ -f "$symlink_path" ]]; then
-#     log_info "Symlink $symlink_path already exists. Will not add again."
-#   else
-#     log_info "Adding symlink to $vault_dest_path in $symlink_path"
-#     sudo ln -s "$vault_dest_path" "$symlink_path"
-#   fi
   
   # Remove garbage
   if [[ "$download_url" != "local" || -n "$version" ]]; then
@@ -248,18 +239,12 @@ function install_binary {
   sudo rm -f /tmp/TermsOfEvaluation.txt
   sudo rm -f /tmp/EULA.txt
 
-
-#   log_info "Copying Vault run script to $run_vault_dest_path"
-#   sudo cp "$SCRIPT_DIR/run-vault" "$run_vault_dest_path"
-#   sudo chown "$username:$username" "$run_vault_dest_path"
-#   sudo chmod a+x "$run_vault_dest_path"
 }
 
 # For more info, see: https://www.vaultproject.io/docs/configuration/#disable_mlock
 function configure_mlock {
   echo "Giving Vault permission to use the mlock syscall"
-  # Requires installing libcap2-bin on Ubuntu 18
-  sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))
+  sudo setcap cap_ipc_lock=+ep $(readlink -f /usr/local/bin/vault)
 }
 
 function install {
@@ -320,11 +305,11 @@ function install {
   configure_mlock
 
 
-  if command -v vault; then
+  if [ -x /usr/local/bin/vault ]; then
     log_info "Vault install complete!"
   else
-    log_info "Could not find vault command. Aborting.";
-    exit 1;
+    log_info "Could not find vault command. Aborting."
+    exit 1
   fi
 }
 
